services:
  - type: web
    name: video-ai-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 1
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 120 --keep-alive 5 --max-requests 100 --max-requests-jitter 10"