services:
  - type: web
    name: ai-assistant
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: XAUTHORITY=/tmp/.Xauthority xvfb-run --server-args="-screen 0 800x600x16" gunicorn --workers=1 --timeout=300 --preload --max-requests=100 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: GOOGLE_API_KEY
        sync: false
      - key: DISPLAY
        value: :99
      - key: FLASK_ENV
        value: production
      - key: XAUTHORITY
        value: /tmp/.Xauthority