services:
  - type: web
    name: ai-assistant
    runtime: python
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12