services:
  - type: web
    name: video-ai-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: True
      - key: WEB_CONCURRENCY
        value: 1
      - key: SECRET_KEY
        generateValue: True
      - key: GOOGLE_API_KEY
        value: AIzaSyBHa6AQZnRgYF4PyBf95u97g7mKVooQZnU
      - key: GUNICORN_TIMEOUT
        value: 120
    disk:
      name: video-ai-disk
      mountPath: /opt/render/data
      sizeGB: 1